# Generated by Django 4.2.10 on 2024-02-18 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_coupon_alter_productimage_image'),
        ('accounts', '0002_cart_cartitems'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CartItems',
            new_name='CartItem',
        ),
    ]
